# Generated by Django 3.2.6 on 2021-08-13 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(allow_unicode=True, max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(allow_unicode=True, max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=100)),
                ('slug', models.SlugField(allow_unicode=True, max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.TextField()),
                ('semester', models.PositiveIntegerField(null=True)),
                ('credit', models.PositiveIntegerField(default=0)),
                ('grade', models.PositiveIntegerField()),
                ('department', models.ManyToManyField(blank=True, null=True, to='lecture.Department')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lecture.division')),
                ('time', models.ManyToManyField(blank=True, null=True, to='lecture.Time')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('grade', models.PositiveIntegerField()),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lecture.department')),
                ('lecture', models.ManyToManyField(blank=True, null=True, to='lecture.Lecture')),
            ],
        ),
    ]
